name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
      - '[0-9]+-*'

permissions: write-all      

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  login:
    name: Registry login test
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest || true
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [login]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Build image
        run: |
          docker build . \
            --tag ${{ env.IMAGE_NAME }}:latest
      - name: Push image
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
      
