# name: Create and publish a Docker image

# # Configures this workflow to run every time a change is pushed to the branch called `release`.
# on:
#   push:
#     branches:
#       - '[0-9]+-*'

# permissions: write-all      
# name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ghcr.io/bcit-ltc/${{ github.event.repository.name }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
