# name: Create and publish a Docker image

# # Configures this workflow to run every time a change is pushed to the branch called `release`.
# on:
#   push:
#     branches:
#       - '[0-9]+-*'

# permissions: write-all      
# name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/bcit-ltc/${{ github.event.repository.name }}:latest
                    